
import 'package:cloud_firestore/cloud_firestore.dart';

class MeasurementModel{
  int? shouldertoShoulder, upperChest, bust, belowBustRound, shapeRound, slitRound, waistRound, hipRound,
  armhole, sleeveLength, sleeveRound, frontNeckDrape, backNeckDrape, neckRound, yokeLength, bustSpan, bustPointLength,
  belowBustLength, shapeLength, waistLength, slitLength, hipLength, frontWidth, backWidth, fullLength, bottomSkirtLength,
  bottomSkirtwaist, thignLengthRound, kneeLengthRound, calfLengthRound, ankleRound;

  MeasurementModel({
    this.shouldertoShoulder,
    this.upperChest,
    this.bust,
    this.belowBustRound,
    this.shapeRound,
    this.slitRound,
    this.waistRound,
    this.hipRound,
    this.armhole,
    this.sleeveLength,
    this.sleeveRound,
    this.frontNeckDrape,
    this.backNeckDrape,
    this.neckRound,
    this.yokeLength,
    this.bustSpan,
    this.bustPointLength,
    this.belowBustLength,
    this.shapeLength,
    this.waistLength,
    this.slitLength,
    this.hipLength,
    this.frontWidth,
    this.backWidth,
    this.fullLength,
    this.bottomSkirtLength,
    this.bottomSkirtwaist,
    this.thignLengthRound,
    this.kneeLengthRound,
    this.calfLengthRound,
    this.ankleRound,
});

  factory MeasurementModel.fromMap(DocumentSnapshot map) {
    return MeasurementModel(
      shouldertoShoulder: map["shouldertoShoulder"],
      upperChest: map["upperChest"],
      bust: map["bust"],
      belowBustRound: map["belowBustRound"],
      shapeRound: map["shapeRound"],
      slitRound: map["slitRound"],
      waistRound: map["waistRound"],
      hipRound: map["hipRound"],
      armhole: map["armhole"],
      sleeveLength: map["sleeveLength"],
      sleeveRound: map["sleeveRound"],
      frontNeckDrape: map["frontNeckDrape"],
      backNeckDrape: map["backNeckDrape"],
      neckRound: map["neckRound"],
      yokeLength: map["yokeLength"],
      bustSpan: map["bustSpan"],
      bustPointLength: map["bustPointLength"],
      belowBustLength: map["belowBustLength"],
      shapeLength: map["shapeLength"],
      waistLength: map["waistLength"],
      slitLength: map["slitLength"],
      hipLength: map["hipLength"],
      frontWidth: map["frontWidth"],
      backWidth: map["backWidth"],
      fullLength: map["fullLength"],
      bottomSkirtLength: map["bottomSkirtLength"],
      bottomSkirtwaist: map["bottomSkirtwaist"],
      thignLengthRound: map["thignLengthRound"],
      kneeLengthRound: map["kneeLengthRound"],
      calfLengthRound: map["calfLengthRound"],
      ankleRound: map["ankleRound"]
    );
  }

  Map<String, dynamic> toMap(){
    return {
      "shouldertoShoulder": shouldertoShoulder,
      "upperChest": upperChest,
      "bust": bust,
      "belowBustRound": belowBustRound,
      "shapeRound": shapeRound,
      "slitRound": slitRound,
      "waistRound": waistRound,
      "hipRound": hipRound,
      "armhole": armhole,
      "sleeveLength": sleeveLength,
      "sleeveRound": sleeveRound,
      "frontNeckDrape": frontNeckDrape,
      "backNeckDrape": backNeckDrape,
      "neckRound": neckRound,
      "yokeLength": yokeLength,
      "bustSpan": bustSpan,
      "bustPointLength": bustPointLength,
      "belowBustLength": belowBustLength,
      "shapeLength": shapeLength,
      "waistLength": waistLength,
      "slitLength": slitLength,
      "hipLength": hipLength,
      "frontWidth": frontWidth,
      "backWidth": backWidth,
      "fullLength": fullLength,
      "bottomSkirtLength": bottomSkirtLength,
      "bottomSkirtwaist": bottomSkirtwaist,
      "thignLengthRound": thignLengthRound,
      "kneeLengthRound": kneeLengthRound,
      "calfLengthRound": calfLengthRound,
      "ankleRound": ankleRound
    };
  }
}